### ISSUE TITLE
Forum test harness fails when there are no posts in the database

### ISSUE THREAD

**Issue by harsimrat99** [CloudClub-uoft/cloud-club-website#66]
The following error is seen when executing: **python test_forum.py** 

Traceback (most recent call last):
  File ".\cloud-club-website\test\frontend\forum\test_forum.py", line 106, in <module>
    test_create_post(driver)
  File ".\cloud-club-website\test\frontend\forum\test_forum.py", line 55, in test_create_post
    total_posts_before = get_total_posts(driver)
  File ".\cloud-club-website\test\frontend\forum\test_forum.py", line 37, in get_total_posts
    return int(split_post_stats[-3]) # total posts
ValueError: invalid literal for int() with base 10: 'No'

**Comment by qingyuan-wu** [comment]
This issue has been resolved. Closing
